using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using EView360Models.ViewModels;
using IronXL;
using Microsoft.JSInterop;
using NPOI.SS.UserModel;
using System.Reflection;

namespace EView360.Data
{
    public class ExcelExport
    {
        public void ExcelGenerate(IJSRuntime iJSRuntime, List<AuditLogViewModel> auditLogViewModels)
        {
            byte[] fileContents;
            WorkBook xlsxWorkbook = WorkBook.Create(IronXL.ExcelFileFormat.XLSX);
            xlsxWorkbook.Metadata.Author = "IronXL";
            //Add a blank WorkSheet
            WorkSheet xlsxSheet = xlsxWorkbook.CreateWorkSheet("new_sheet");
            //Add data and styles to the new worksheet

            //Type type = auditLogViewModels.GetType();
            //PropertyInfo[] props = type.GetProperties();
            //foreach (var item in props)
            //{

            //}

            xlsxSheet["A1"].Value = "Product EN";
            xlsxSheet["B1"].Value = "SKU";
            xlsxSheet["C1"].Value = "Customer";
            xlsxSheet["A1:C1"].Style.Font.Bold = true;

            xlsxSheet["A2"].Value = "Iron Rods";
            xlsxSheet["A3"].Value = "Mobile Phones";
            xlsxSheet["A4"].Value = "Chargers";
            xlsxSheet["B2"].Value = "105";
            xlsxSheet["B3"].Value = "285";
            xlsxSheet["B4"].Value = "301";
            xlsxSheet["C2"].Value = "Adam";
            xlsxSheet["C3"].Value = "Ellen";
            xlsxSheet["C4"].Value = "Tom";

            

            Type type = auditLogViewModels.GetType();
            PropertyInfo[] props = type.GetProperties();



            using (var workbook = new XLWorkbook())
            {

                IXLWorksheet worksheet =
                workbook.Worksheets.Add("Activity");
                int i = 0;
                //foreach (var item in props)
                //{
                //    i++;
                //    worksheet.Cell(1, i).Value = item.Name;
                ////}
                //worksheet.Cell(1, 1).Value = "Activity";
                //worksheet.Cell(1, 2).Value = "Total :";
                //worksheet.Cell(1, 3).Value = auditLogViewModels.Count();
                //worksheet.Cell(1, 4).Value = $"Generated On:";
                //worksheet.Cell(1, 4).Value = $"{DateTime.Now.Date.ToString("dd/MM/yyyy")}";
                //worksheet.Cell(1, 5).Value = $"{DateTime.Now.ToString("HH:mm")}";
                //worksheet.Cell(1, 6).Value = $"Generated By:";
                //worksheet.Cell(1, 7).Value = $"[Name]";

                worksheet.Cell(2, 1).Value = "Name";
                worksheet.Cell(2, 2).Value = "ActivityTime";
                worksheet.Cell(2, 3).Value = "Description";
                for (int index = 2; index <= auditLogViewModels.Count; index++)
                {
                    worksheet.Cell(index + 1, 1).Value = auditLogViewModels[index - 1].UserLoginName;
                    worksheet.Cell(index + 1, 2).Value = auditLogViewModels[index - 1].ActivityTime;
                    worksheet.Cell(index + 1, 3).Value = auditLogViewModels[index - 1].Message;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    fileContents = content;
                    iJSRuntime.InvokeAsync<ExcelExport>(
                        "saveAsFile",
                        $"ActivityLog{DateTime.Now.ToString("ddMMyyyy")}.xlsx",
                        Convert.ToBase64String(fileContents)
                    );
                }
            }
            
           
        }
    }
}