<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>395478d6-0d2a-4b0d-ac6e-5639365ff9e7</UserSecretsId>
		<DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" Version="4.3.0" />
		<PackageReference Include="Blazored.SessionStorage.TestExtensions" Version="2.3.0" />
		<PackageReference Include="Blazored.SessionStorage" Version="2.3.0" />
		<PackageReference Include="Blazorise.Bootstrap" Version="1.1.6" />
		<PackageReference Include="Blazorise.Charts" Version="1.1.6" />
		<PackageReference Include="Blazorise.Components" Version="1.1.6" />
		<PackageReference Include="Blazorise.DataGrid" Version="1.1.6" />
		<PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.1.6" />
		<PackageReference Include="Blazorise.LoadingIndicator" Version="1.1.6" />
		<PackageReference Include="ClosedXML" Version="0.100.3" />
		<PackageReference Include="EPPlus" Version="6.1.2" />
		<PackageReference Include="IronXL.Excel" Version="2023.1.14" />
		<PackageReference Include="iTextSharp" Version="5.5.13.3" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.5" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="7.0.12" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
		<PackageReference Include="NPOI" Version="2.6.0" />
		<PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
		<PackageReference Include="System.DirectoryServices.AccountManagement" Version="7.0.1" />
 	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\DataRequestorLayer\DataRequestor\DataRequestor\DataRequestor.csproj" />
		<ProjectReference Include="..\..\EView360Models\EView360Models\EView360Models.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ceTe.DynamicPDF.20">
		  <HintPath>..\..\Common\ExternalDependencies\ceTe.DynamicPDF.20.dll</HintPath>
		</Reference>
		<Reference Include="Common">
			<HintPath>..\..\Common\bin\Debug\net7.0\Common.dll</HintPath>
		</Reference>
		<Reference Include="DataRequestorMiddleware">
		  <HintPath>..\..\Services\DataRequestorMiddleware\DataRequestorMiddleware\bin\Debug\net7.0\DataRequestorMiddleware.dll</HintPath>
		</Reference>
		<Reference Include="Encryption">
		  <HintPath>..\..\Common\ExternalDependencies\Encryption.dll</HintPath>
		</Reference>
		<Reference Include="Interop.LicenseVerifierLib">
		  <HintPath>..\..\..\CCMS\Interop.LicenseVerifierLib.dll</HintPath>
		</Reference>
	 
	</ItemGroup>

</Project>
