CREATE TYPE [dbo].[ATM_table_type] AS TABLE(
	[ATM_id] [bigint] NOT NULL,
	[last_status_reply] [varchar](128) NULL,
	[region_id] [bigint] NOT NULL,
	[title] [varchar](256) NOT NULL,
	[IP] [varchar](20) NOT NULL,
	[port] [int] NOT NULL,
	[modified_by] [bigint] NULL,
	[created_by] [bigint] NOT NULL,
	[is_active] [bit] NOT NULL,
	[creation_time] [datetime] NOT NULL,
	[atm_type] [varchar](25) NOT NULL,
	[cassette1_capacity] [int] NOT NULL,
	[cassette1_denomination] [int] NOT NULL,
	[cassette2_capacity] [int] NOT NULL,
	[cassette2_denomination] [int] NOT NULL,
	[cassette3_denomination] [int] NOT NULL,
	[cassette3_capacity] [int] NOT NULL,
	[cassette4_denomination] [int] NOT NULL,
	[cassette4_capacity] [int] NOT NULL,
	[cassette5_denomination] [int] NOT NULL,
	[cassette5_capacity] [int] NOT NULL,
	[cassette6_denomination] [int] NOT NULL,
	[cassette6_capacity] [int] NOT NULL,
	[cassette7_denomination] [int] NOT NULL,
	[cassette7_capacity] [int] NOT NULL,
	[is_healthy] [bit] NOT NULL,
	[location] [varchar](500) NULL,
	[address1] [varchar](500) NULL,
	[address2] [varchar](500) NULL,
	[city] [varchar](30) NULL,
	[country] [varchar](30) NULL,
	[max_notes_per_cassette] [int] NULL,
	[min_operating_balance] [decimal](18, 0) NULL,
	[is_atm] [bit] NULL,
	[is_cdm] [bit] NULL,
	[is_ccdm] [bit] NULL,
	[cdm_cassette1_capacity] [int] NULL,
	[cdm_cassette2_capacity] [int] NULL,
	[cdm_cassette3_capacity] [int] NULL,
	[cdm_cassette4_capacity] [int] NULL,
	[ccdm_cassette1_capacity] [int] NULL,
	[ccdm_cassette2_capacity] [int] NULL,
	[ccdm_cassette3_capacity] [int] NULL,
	[ccdm_cassette4_capacity] [int] NULL,
	[cdm_cassette1_threshold] [int] NULL,
	[cdm_cassette2_threshold] [int] NULL,
	[cdm_cassette3_threshold] [int] NULL,
	[cdm_cassette4_threshold] [int] NULL,
	[ccdm_cassette1_threshold] [int] NULL,
	[ccdm_cassette2_threshold] [int] NULL,
	[ccdm_cassette3_threshold] [int] NULL,
	[ccdm_cassette4_threshold] [int] NULL,
	[note_set_type_id] [bigint] NOT NULL,
	[ccdm_cassette5_capacity] [int] NULL,
	[ccdm_cassette5_threshold] [int] NULL,
	[startup_sleep_interval] [int] NULL,
	[debug_level] [tinyint] NULL,
	[purge1_threshold] [int] NULL,
	[is_purge1_threshold_selected] [bit] NULL,
	[purge2_threshold] [int] NULL,
	[is_purge2_threshold_selected] [bit] NULL,
	[purge3_threshold] [int] NULL,
	[is_purge3_threshold_selected] [bit] NULL,
	[purge4_threshold] [int] NULL,
	[is_purge4_threshold_selected] [bit] NULL,
	[purge5_threshold] [int] NULL,
	[is_purge5_threshold_selected] [bit] NULL,
	[purge6_threshold] [int] NULL,
	[is_purge6_threshold_selected] [bit] NULL,
	[purge7_threshold] [int] NULL,
	[is_purge7_threshold_selected] [bit] NULL,
	[retry_count_conf_upload] [int] NOT NULL,
	[TCPTimeout] [int] NOT NULL,
	[SleepInterval] [int] NOT NULL,
	[Type1MinimumNotes] [int] NOT NULL,
	[Type2MinimumNotes] [int] NOT NULL,
	[Type3MinimumNotes] [int] NOT NULL,
	[Type4MinimumNotes] [int] NOT NULL,
	[Type5MinimumNotes] [int] NOT NULL,
	[Type6MinimumNotes] [int] NOT NULL,
	[Type7MinimumNotes] [int] NOT NULL,
	[allowed_inactivity_period] [int] NULL,
	[description] [varchar](200) NULL,
	[cheque_allowed_inactivity_period] [int] NULL,
	[bna_allowed_inactivity_period] [int] NULL,
	[out_of_cash_threshold] [int] NOT NULL,
	[longitude] [varchar](20) NULL,
	[latitude] [varchar](20) NULL,
	[is_swap_default_replenishment] [bit] NULL,
	[message_processor_id] [bigint] NULL,
	[type1_min_notes_threshold] [int] NULL,
	[type2_min_notes_threshold] [int] NULL,
	[type3_min_notes_threshold] [int] NULL,
	[type4_min_notes_threshold] [int] NULL,
	[type1_min_notes_threshold_value] [int] NULL,
	[type2_min_notes_threshold_value] [int] NULL,
	[type3_min_notes_threshold_value] [int] NULL,
	[type4_min_notes_threshold_value] [int] NULL,
	[bna_allowed_inactivity_period_normal_days] [int] NULL,
	[bna_allowed_inactivity_period_salary_days] [int] NULL,
	[cheque_allowed_inactivity_period_normal_days] [int] NULL,
	[cheque_allowed_inactivity_period_salary_days] [int] NULL,
	[cit_id] [bigint] NULL,
	[is_recycler] [int] NULL,
	[last_ping_status] [varchar](100) NULL,
	[last_ping_executed_at] [datetime] NULL,
	[last_telnet_status] [varchar](100) NULL,
	[last_telnet_executed_at] [datetime] NULL,
	[assigned_server] [int] NULL,
	[is_edited] [bit] NULL,
	[retry_count_counter_file] [int] NULL,
	[atm_streaming_heartbeat_received_at] [datetime] NULL,
	[atm_on_demand_heartbeat_received_at] [datetime] NULL
)
GO
